- name: Setup Redis and Frontend Servers
  hosts:
    - server_role_redis_server
    - server_role_frontend_server
  become: true
  gather_facts: yes # Collect facts only once for the entire play
  roles:
    - redis
    - frontend

  vars:
    # Set remote_user conditionally for each server role
    ansible_user: "{{ 'rocky' if 'server_role_redis_server' in group_names else 'ubuntu' }}"

# - name: Setup Redis Servers
#   hosts: server_role_redis_server
#   become: true


# - name: Setup Frontend Servers
#   hosts: server_role_frontend_server
#   become: true
#   roles:
